name: Load data in CosmosDB

on:
  workflow_dispatch:

jobs:
  load-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync
        working-directory: utility

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Get Cosmos DB connection string
      #   id: cosmos
      #   run: |
      #       CONNECTION_STRING=$(az cosmosdb keys list \
      #         --name ${{ secrets.COSMOS_DB_NAME }} \
      #         --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #         --type connection-strings \
      #         --query "connectionStrings[0].connectionString" \
      #         --output tsv)
      #       if [ -z "$CONNECTION_STRING" ]; then
      #         echo "ERROR: Failed to retrieve Cosmos DB connection string"
      #         exit 1
      #       fi
      #       echo "::add-mask::$CONNECTION_STRING"
      #       echo "connection_string=$CONNECTION_STRING" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo ${{ secrets.COSMOS_DB_NAME }}
          echo ${{ secrets.AZURE_RESOURCE_GROUP }}

      # - name: Run agents creation script
      #   id: create-agent
      #   # env:
      #   #     COSMOS_DB_CONNECTION_STRING: ${{ steps.cosmos.outputs.connection_string }}
      #   run: |
      #     CONNECTION_STRING=$(az cosmosdb keys list \
      #       --name ${{ secrets.COSMOS_DB_NAME }} \
      #       --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #       --type connection-strings \
      #       --query "connectionStrings[0].connectionString" \
      #       --output tsv)
      #     if [ -z "$CONNECTION_STRING" ]; then
      #       echo "ERROR: Failed to retrieve Cosmos DB connection string"
      #       exit 1
      #     fi
      #     export COSMOS_DB_CONNECTION_STRING="$CONNECTION_STRING"
      #     uv run data_loader.py
      #   working-directory: utility
